kind: Deployment
apiVersion: apps/v1
metadata:
  name: currency-converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: currency-converter
        image: localhost:5000/currency-converter
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      restartPolicy: Always
