kind: Service
apiVersion: v1
metadata:
  name: currency-converter
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: currency-converter
